# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historialVentas.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.controladorHistorial import ControladorHistorial

class HistorialVentas(object):

    def __init__(self):
        self.historial = ControladorHistorial(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1057, 577)
        Dialog.setFixedSize(1057, 577) 
        icon = QtGui.QIcon("Recursos/historial.ico")  # Ruta de la imagen del icono
        Dialog.setWindowIcon(icon)


        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 1061, 31))
        self.label_4.setStyleSheet("background-color: rgb(145, 145, 145);\n"
"font: 87 14pt \"Arial Black\";\n"
"color: rgb(249, 249, 249);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.tablaHistorialVentas = QtWidgets.QTableWidget(Dialog)
        self.tablaHistorialVentas.setGeometry(QtCore.QRect(10, 40, 1041, 531))
        self.tablaHistorialVentas.setObjectName("tablaHistorialVentas")
        self.tablaHistorialVentas.setColumnCount(10)
        self.tablaHistorialVentas.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaHistorialVentas.setHorizontalHeaderItem(9, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.historial.actualizar_historial()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Historial Ventas", "Historial Ventas"))
        self.label_4.setText(_translate("Dialog", "Historial Ventas"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "venta"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "factura"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "empleado"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "nombre"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "cliente"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "fecha"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "producto"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "nombre producto"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "cantidad"))
        item = self.tablaHistorialVentas.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "precio unitario"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = HistorialVentas()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
