# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mockupLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from Controllers.controladorLogin import LogInController

from PyQt5 import QtCore, QtGui, QtWidgets
from Controllers.UsuarioExistente import UsuarioExistenteError
from Views.AdministradorFerreteria import Administrador
from Views.empleadoFerreteria import Empleado
from Views.AdministradorFerreteria import Administrador

class Ui_Dialog(object):
    
    def __init__(self,parent=None):
        self.login_controller = LogInController()
        self.usuario_existe = UsuarioExistenteError()
        self.parent = parent
    
    def setupUi(self, Dialog):
        Dialog.setObjectName("Inicio Sesion")
        Dialog.resize(330, 300)
        self.lbl_inicioSesion = QtWidgets.QLabel(Dialog)
        self.lbl_inicioSesion.setGeometry(QtCore.QRect(-40, 0, 411, 51))
        self.lbl_inicioSesion.setStyleSheet("background-color: rgb(12, 67, 139);\n"
"font: 87 14pt \"Arial Black\";\n"
"color: rgb(243, 243, 243);")
        self.lbl_inicioSesion.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_inicioSesion.setObjectName("lbl_inicioSesion")
        self.lbl_espacioEnBlanco = QtWidgets.QLabel(Dialog)
        self.lbl_espacioEnBlanco.setEnabled(False)
        self.lbl_espacioEnBlanco.setGeometry(QtCore.QRect(0, 50, 330, 10))
        self.lbl_espacioEnBlanco.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.lbl_espacioEnBlanco.setText("")
        self.lbl_espacioEnBlanco.setObjectName("lbl_espacioEnBlanco")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 60, 331, 211))
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.0511364 rgba(16, 93, 140, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 8pt \"Arial Black\";\n"
"font: 87 10pt \"Arial Black\";")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.usuarioInput = QtWidgets.QLineEdit(Dialog)
        self.usuarioInput.setGeometry(QtCore.QRect(90, 110, 151, 21))
        self.usuarioInput.setObjectName("usuarioInput")
        self.usuarioContrasenia = QtWidgets.QLineEdit(Dialog)
        self.usuarioContrasenia.setGeometry(QtCore.QRect(90, 150, 151, 21))
        self.usuarioContrasenia.setObjectName("usuarioContrasenia")
        self.usuarioContrasenia.setEchoMode(QtWidgets.QLineEdit.Password)
        self.BtnIngresar = QtWidgets.QPushButton(Dialog)
        self.BtnIngresar.setGeometry(QtCore.QRect(130, 210, 75, 23))
        self.BtnIngresar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.0511364 rgba(16, 93, 140, 255), stop:1 rgba(255, 255, 255, 255));")
        self.BtnIngresar.setObjectName("BtnIngresar")
        self.BtnIngresar.clicked.connect(self.ObtenerDatos)
        self.lbl_alertaUsuarioContrasenia = QtWidgets.QLabel(Dialog)
        self.lbl_alertaUsuarioContrasenia.setGeometry(QtCore.QRect(0, 265, 331, 31))
        self.lbl_alertaUsuarioContrasenia.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.lbl_alertaUsuarioContrasenia.setText("")
        self.lbl_alertaUsuarioContrasenia.setObjectName("lbl_alertaUsuarioContrasenia")
        self.contraseniaOlvidada = QtWidgets.QLabel(Dialog)
        self.contraseniaOlvidada.setGeometry(QtCore.QRect(110, 240, 131, 16))
        self.contraseniaOlvidada.setStyleSheet("color: rgb(20, 165, 255);")
        self.contraseniaOlvidada.setObjectName("contraseniaOlvidada")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Inicio Sesion", "Inicio Sesion"))
        self.lbl_inicioSesion.setText(_translate("Inicio Sesion", "Inicio de Sesión"))
        self.usuarioInput.setPlaceholderText(_translate("Inicio Sesion", "Ingresa tu usuario"))
        self.usuarioContrasenia.setPlaceholderText(_translate("Inicio Sesion", "Ingresa tu contraseña"))
        self.BtnIngresar.setText(_translate("Inicio Sesion", "Ingresar"))
        self.contraseniaOlvidada.setText(_translate("Inicio Sesion", "¿Olvidaste la contraseña?"))



    def ObtenerDatos(self):
        usuario = str(self.usuarioInput.text())
        contraseña = str(self.usuarioContrasenia.text())
        controlador = self.login_controller.log_in(usuario, contraseña,Administrador,Empleado,Ui_Dialog)
        administrador = Administrador
        log_in = Ui_Dialog
        if controlador == True:
            print("reconocido")
            self.lbl_alertaUsuarioContrasenia.setText(f'Bienvenido, {usuario}')
            self.lbl_alertaUsuarioContrasenia.setStyleSheet('background:green;color:white')
            self.parent.hide()
        else:
            print("NO reconocido")
            self.lbl_alertaUsuarioContrasenia.setText('Usuario y/o contraseña incorrectos.')
            self.lbl_alertaUsuarioContrasenia.setStyleSheet('background:tomato;color:white')

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    











































    # def ObtenerDatos(self):
    #     usuario = str(self.usuarioInput.text())
    #     contraseña = str(self.usuarioContrasenia.text())
    #     try:
    #         self.login_controller.log_in(usuario,contraseña)
    #         self.lbl_alertaUsuarioContrasenia.setText(f'Bienvenido, {usuario}')
    #         self.lbl_alertaUsuarioContrasenia.setStyleSheet('background:green;color:white')
    #     except UsuarioExistenteError as e:
    #         self.lbl_alertaUsuarioContrasenia.setText(str(e))
    #         self.lbl_alertaUsuarioContrasenia.setStyleSheet('background:tomato;color:white')
        