# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'opcionesEmpleados.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)


from Controllers.controladorEmpleados import EmpleadoControlador
from PyQt5.QtGui import QIntValidator
from Views.registrar import RegistrarEmpleado

class OpcionesEmpleados(object):
    def __init__(self):
        self.controlador_empleados = EmpleadoControlador(self)
        
        


    def setupUi(self,Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(720, 630)
        Dialog.setFixedSize(720, 630)
        icon = QtGui.QIcon("Recursos/empleado.ico")  # Ruta de la imagen del icono
        Dialog.setWindowIcon(icon)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 721, 31))
        self.label.setStyleSheet("background-color: rgb(145, 145, 145);\n"
"font: 87 14pt \"Arial Black\";\n"
"color: rgb(249, 249, 249);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.int_validator = QIntValidator()
        self.btnModificarEmpleado = QtWidgets.QPushButton(Dialog)
        self.btnModificarEmpleado.setGeometry(QtCore.QRect(540, 370, 121, 23))
        self.btnModificarEmpleado.setObjectName("btnModificarEmpleado")
        self.btnModificarEmpleado.setEnabled(False)
        self.btnModificarEmpleado.clicked.connect(self.controlador_empleados.modificar)
        self.nombre_empleado = QtWidgets.QLineEdit(Dialog)
        self.nombre_empleado.setGeometry(QtCore.QRect(120, 130, 113, 20))
        self.nombre_empleado.setObjectName("nombre_empleado")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(510, 70, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.clicked.connect(self.modificarEmpleado)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 110, 121, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(460, 30, 20, 371))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.empleado_eliminar = QtWidgets.QComboBox(Dialog)
        self.empleado_eliminar.setGeometry(QtCore.QRect(380, 90, 69, 22))
        self.empleado_eliminar.setObjectName("empleado_eliminar")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(270, 90, 101, 16))
        self.label_9.setObjectName("label_9")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(243, 30, 20, 361))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnAgregarEmpleado = QtWidgets.QPushButton(Dialog)
        self.btnAgregarEmpleado.setGeometry(QtCore.QRect(70, 340, 121, 23))
        self.btnAgregarEmpleado.setObjectName("btnAgregarEmpleado")
        self.btnAgregarEmpleado.clicked.connect(self.obtenerDatos)
        self.btnBuscarEmpleado = QtWidgets.QLineEdit(Dialog)
        self.btnBuscarEmpleado.setGeometry(QtCore.QRect(560, 70, 113, 20))
        self.btnBuscarEmpleado.setObjectName("btnBuscarEmpleado")
        self.btnBuscarEmpleado.setValidator(self.int_validator)
        self.btnEliminarEmpleado = QtWidgets.QPushButton(Dialog)
        self.btnEliminarEmpleado.setGeometry(QtCore.QRect(300, 150, 121, 23))
        self.btnEliminarEmpleado.setObjectName("btnEliminarEmpleado")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 101, 16))
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(470, 140, 231, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.cedula_empleado = QtWidgets.QLineEdit(Dialog)
        self.cedula_empleado.setGeometry(QtCore.QRect(120, 90, 113, 20))
        self.cedula_empleado.setObjectName("cedula_empleado")
        
        self.cedula_empleado.setValidator(self.int_validator)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 51, 16))
        self.label_6.setObjectName("label_6")
        self.telefono_empleado = QtWidgets.QLineEdit(Dialog)
        self.telefono_empleado.setGeometry(QtCore.QRect(120, 170, 113, 20))
        self.telefono_empleado.setObjectName("telefono_empleado")
        self.int_validator = QIntValidator()
        self.telefono_empleado.setValidator(self.int_validator)
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(0, 390, 721, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(520, 0, 41, 31))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/logoFerreteria/logoferreteria.png-HD.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(60, 40, 141, 21))
        self.label_20.setStyleSheet("font: 8pt \"Arial\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(290, 40, 141, 21))
        self.label_21.setStyleSheet("font: 8pt \"Arial\";")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(520, 40, 141, 21))
        self.label_22.setStyleSheet("font: 8pt \"Arial\";")
        self.label_22.setObjectName("label_22")
        self.email_empleado = QtWidgets.QLineEdit(Dialog)
        self.email_empleado.setGeometry(QtCore.QRect(120, 210, 113, 20))
        self.email_empleado.setObjectName("email_empleado")
        self.apellido_empleado = QtWidgets.QLineEdit(Dialog)
        self.apellido_empleado.setGeometry(QtCore.QRect(120, 250, 113, 20))
        self.apellido_empleado.setObjectName("apellido_empleado")
        self.direccion_empleado = QtWidgets.QLineEdit(Dialog)
        self.direccion_empleado.setGeometry(QtCore.QRect(120, 290, 113, 20))
        self.direccion_empleado.setObjectName("direccion_empleado")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 210, 47, 21))
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 250, 47, 13))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 290, 51, 16))
        self.label_8.setObjectName("label_8")
        self.listaEmpleados = QtWidgets.QScrollArea(Dialog)
        self.listaEmpleados.setGeometry(QtCore.QRect(40, 410, 231, 201))
        self.listaEmpleados.setWidgetResizable(True)
        self.listaEmpleados.setObjectName("listaEmpleados")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 199))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listaEmpleados.setWidget(self.scrollAreaWidgetContents)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(490, 170, 101, 16))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(490, 330, 51, 16))
        self.label_12.setObjectName("label_12")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(490, 250, 47, 21))
        self.label_4.setObjectName("label_4")
        self.nuevo_nombre_empleado = QtWidgets.QLineEdit(Dialog)
        self.nuevo_nombre_empleado.setGeometry(QtCore.QRect(590, 170, 113, 20))
        self.nuevo_nombre_empleado.setObjectName("nuevo_nombre_empleado")
        self.nuevo_nombre_empleado.setReadOnly(True)
        self.nuevo_telefono_empleado = QtWidgets.QLineEdit(Dialog)
        self.nuevo_telefono_empleado.setGeometry(QtCore.QRect(590, 210, 113, 20))
        self.nuevo_telefono_empleado.setObjectName("nuevo_telefono_empleado")
        self.nuevo_telefono_empleado.setValidator(self.int_validator)
        self.nuevo_telefono_empleado.setReadOnly(True)
        self.nuevo_apellido_empleado = QtWidgets.QLineEdit(Dialog)
        self.nuevo_apellido_empleado.setGeometry(QtCore.QRect(590, 290, 113, 20))
        self.nuevo_apellido_empleado.setObjectName("nuevo_apellido_empleado")
        self.nuevo_apellido_empleado.setReadOnly(True)
        self.nueva_direccion_empleado = QtWidgets.QLineEdit(Dialog)
        self.nueva_direccion_empleado.setGeometry(QtCore.QRect(590, 330, 113, 20))
        self.nueva_direccion_empleado.setObjectName("nueva_direccion_empleado")
        self.nueva_direccion_empleado.setReadOnly(True)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(490, 290, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(490, 210, 51, 16))
        self.label_14.setObjectName("label_14")
        self.nuevo_email_empleado = QtWidgets.QLineEdit(Dialog)
        self.nuevo_email_empleado.setGeometry(QtCore.QRect(590, 250, 113, 20))
        self.nuevo_email_empleado.setObjectName("nuevo_email_empleado")
        self.nuevo_email_empleado.setReadOnly(True)
        self.cedulas()
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Opciones Empleado", "Opciones Empleado"))
        self.label.setText(_translate("Dialog", "Empleados"))
        self.btnModificarEmpleado.setText(_translate("Dialog", "Modificar Empleado"))
        self.label_11.setText(_translate("Dialog", "Cedula"))
        self.label_3.setText(_translate("Dialog", "Cedula Empleado"))
        self.pushButton_3.setText(_translate("Dialog", "Buscar"))
        self.label_9.setText(_translate("Dialog", "Empleado a Eliminar"))
        self.btnAgregarEmpleado.setText(_translate("Dialog", "Agregar Empleado"))
        self.btnEliminarEmpleado.setText(_translate("Dialog", "Eliminar Empleado"))
        self.btnEliminarEmpleado.clicked.connect(self.eliminar_empleado)
        self.label_5.setText(_translate("Dialog", "Nombre Empleado"))
        self.label_6.setText(_translate("Dialog", "Telefono"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Agregar Empleado</span></p><p><br/></p></body></html>"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Eliminar Empleado</span></p><p><br/></p></body></html>"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Modificar Empleado</span></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Email"))
        self.label_7.setText(_translate("Dialog", "Apellido"))
        self.label_8.setText(_translate("Dialog", "Direccion"))
        self.label_10.setText(_translate("Dialog", "Nombre Empleado"))
        self.label_12.setText(_translate("Dialog", "Direccion"))
        self.label_4.setText(_translate("Dialog", "Email"))
        self.label_13.setText(_translate("Dialog", "Apellido"))
        self.label_14.setText(_translate("Dialog", "Telefono"))

        
    def eliminar_empleado(self):
    
        elemento_seleccionado = self.empleado_eliminar.currentText()
        self.controlador_empleados.eliminarEmpleado(elemento_seleccionado)
        self.cedulas()
        
        
    def cedulas(self):
        self.empleado_eliminar.clear()
        cedulas = self.controlador_empleados.obtenerCedulas()
        self.empleado_eliminar.addItem("Seleccionar cédula")
        for cedula in cedulas:
            self.empleado_eliminar.addItem(cedula[0])
        self.empleado_eliminar.setCurrentIndex(0)
    
    
    def obtenerDatos(self):
        
        cedula = self.cedula_empleado.text()
        nombre = self.nombre_empleado.text()
        telefono = self.telefono_empleado.text()
        email = self.email_empleado.text()
        apellido = self.apellido_empleado.text()
        direccion = self.direccion_empleado.text() 
        empleado_eliminar = self.empleado_eliminar
        self.controlador_empleados.validarDatos(cedula,nombre,telefono,email,apellido,direccion,RegistrarEmpleado)
        self.cedulas()
        
    def modificarEmpleado(self):
        cedula = self.btnBuscarEmpleado.text()
        self.controlador_empleados.modificarEmpleado(cedula)    
    
    # def abrirVentana(self):
    #     self.controlador_empleados.abrirVentana(OpcionesEmpleados)
        
        

from Recursos.imagenesPyQt5_rc import *
# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = OpcionesEmpleados()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
