# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets 
import sys
import os
myDir = os.getcwd()
sys.path.append(myDir)

from Controllers.RegistrarControlador import Registrar
from Controllers.UsuarioExistente import UsuarioExistenteError
from Models.User import User
from Database.Conection import connection


class RegistrarEmpleado(object):
    
    def __init__(self):
        # Aquí puedes realizar inicializaciones si es necesario
        self.registro_controlador = Registrar()
        self.usuario_existe = UsuarioExistenteError()
        self.user = User(connection())
    def setupUi(self, Dialog):
        Dialog.setObjectName("AeroNorte")
        Dialog.resize(355, 352)
        Dialog.setFixedSize(355,352)
        self.lbl_Registrar = QtWidgets.QLabel(Dialog)
        self.lbl_Registrar.setGeometry(QtCore.QRect(-30, 0, 411, 51))
        self.lbl_Registrar.setStyleSheet("background-color: rgb(183, 200, 238);\n"
"font: 87 14pt \"Arial Black\";\n"
"color: rgb(243, 243, 243);")
        self.lbl_Registrar.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_Registrar.setObjectName("lbl_Registrar")
        self.lbl_espacioEnBlanco_2 = QtWidgets.QLabel(Dialog)
        self.lbl_espacioEnBlanco_2.setEnabled(False)
        self.lbl_espacioEnBlanco_2.setGeometry(QtCore.QRect(0, 50, 361, 16))
        self.lbl_espacioEnBlanco_2.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.lbl_espacioEnBlanco_2.setText("")
        self.lbl_espacioEnBlanco_2.setObjectName("lbl_espacioEnBlanco_2")
        self.lbl_degradadoAzul = QtWidgets.QLabel(Dialog)
        self.lbl_degradadoAzul.setGeometry(QtCore.QRect(0, 60, 361, 271))
        self.lbl_degradadoAzul.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0.0227273 rgba(64, 70, 70, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 87 8pt \"Arial Black\";\n"
"font: 87 10pt \"Arial Black\";")
        self.lbl_degradadoAzul.setText("")
        self.lbl_degradadoAzul.setObjectName("lbl_degradadoAzul")
        self.lbl_alertaUsuarioContrasenia_2 = QtWidgets.QLabel(Dialog)
        self.lbl_alertaUsuarioContrasenia_2.setGeometry(QtCore.QRect(0, 330, 361, 21))
        self.lbl_alertaUsuarioContrasenia_2.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.lbl_alertaUsuarioContrasenia_2.setText("")
        self.lbl_alertaUsuarioContrasenia_2.setObjectName("lbl_alertaUsuarioContrasenia_2")
        self.inputUsuario = QtWidgets.QLineEdit(Dialog)
        self.inputUsuario.setGeometry(QtCore.QRect(110, 150, 151, 21))
        self.inputUsuario.setObjectName("inputUsuario")
        self.inputContrasenia = QtWidgets.QLineEdit(Dialog)
        self.inputContrasenia.setGeometry(QtCore.QRect(110, 200, 151, 21))
        self.inputContrasenia.setObjectName("inputContrasenia")
        self.BtnIngresar_2 = QtWidgets.QPushButton(Dialog)
        self.BtnIngresar_2.setGeometry(QtCore.QRect(150, 250, 75, 23))
        self.BtnIngresar_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.0511364 rgba(16, 93, 140, 255), stop:1 rgba(255, 255, 255, 255));")
        self.BtnIngresar_2.setObjectName("BtnIngresar_2")
        self.BtnIngresar_2.clicked.connect(self.obtenerDatos)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(110, 80, 141, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(280, 70, 61, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/logoFerreteria/logoferreteria.png-HD.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("AeroNorte", "AeroNorte"))
        self.lbl_Registrar.setText(_translate("Dialog", "Registrar"))
        self.inputUsuario.setPlaceholderText(_translate("Dialog", "Crea usuario"))
        self.inputContrasenia.setPlaceholderText(_translate("Dialog", "crea contraseña"))
        self.BtnIngresar_2.setText(_translate("Dialog", "Registrar"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:22pt; font-style:italic; color:#4d73c6;\">Aero</span><span style=\" font-size:22pt; font-style:italic; color:#f4340d;\">Norte</span></p></body></html>"))
        

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Registrar Empleado", "Registrar Empleado"))
        self.lbl_Registrar.setText(_translate("Registrar Empleado", "Registrar"))
        self.inputUsuario.setPlaceholderText(_translate("Registrar Empleado", "Crea usuario"))
        self.inputContrasenia.setPlaceholderText(_translate("Registrar Empleado", "crea contraseña"))
        self.BtnIngresar_2.setText(_translate("Registrar Empleado", "Registrar"))
        

    def obtenerDatos(self):
        usuario = str(self.inputUsuario.text())
        contraseña = str(self.inputContrasenia.text())
        
        try:
            self.registro_controlador.Datos(usuario,contraseña)
            self.lbl_alertaUsuarioContrasenia_2.setText("Usuario registrado correctamente.")
            self.lbl_alertaUsuarioContrasenia_2.setStyleSheet('background:green;color:white')
        except UsuarioExistenteError as e:
            self.lbl_alertaUsuarioContrasenia_2.setText(str(e))
            self.lbl_alertaUsuarioContrasenia_2.setStyleSheet('background:tomato;color:white')



from Recursos.imagenesPyQt5_rc import *


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
